DEFAULT_LLAMA_CPP_BIN_DIR = "C:\\Users\\gabri\\Downloads\\llama-b10424-bin-win-cuda-12.4-x64"
DEFAULT_LLAMA_CPP_SERVER_COMMAND = f"{DEFAULT_LLAMA_CPP_BIN_DIR}\\llama-server.exe"
DEFAULT_LLAMA_CPP_MODEL = "C:\\Users\\gabri\\Downloads\\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf"
DEFAULT_LLAMA_CPP_MMPROJ = "C:\\Users\\gabri\\Downloads\\mmproj-BF16(5).gguf"
DEFAULT_LLAMA_CPP_MTP_MODEL = "C:\\Users\\gabri\\Downloads\\mtp-gemma-4-12B-it(1).gguf"
DEFAULT_LLAMA_CPP_SPEC_DRAFT_N_MAX = 3
DEFAULT_TEXT_LLAMA_CPP_MODEL = DEFAULT_LLAMA_CPP_MODEL
DEFAULT_TEXT_LLAMA_CPP_MMPROJ = None
DEFAULT_EXERCISE_CONTRACT_LLAMA_CPP_MODEL = DEFAULT_TEXT_LLAMA_CPP_MODEL
DEFAULT_EXERCISE_CONTRACT_LLAMA_CPP_MMPROJ = DEFAULT_TEXT_LLAMA_CPP_MMPROJ
# Motion discovery and validation are structured classification tasks. Greedy
# decoding removes run-to-run candidate drift and avoids stochastic expansions
# that can multiply the number of reviewed chunks.
DEFAULT_LLAMA_CPP_TEMPERATURE = 0.0
DEFAULT_LLAMA_CPP_TOP_P = 1.0
DEFAULT_LLAMA_CPP_TOP_K = 0
DEFAULT_LLAMA_CPP_REASONING_BUDGET = 64
DEFAULT_LLAMA_CPP_REASONING_BUDGET_MESSAGE = "Now stop thinking and return the JSON object."
DEFAULT_LLAMA_CPP_CTX_SIZE = 8192
DEFAULT_LLAMA_CPP_BATCH_SIZE = 256
DEFAULT_LLAMA_CPP_UBATCH_SIZE = 512
DEFAULT_LLAMA_CPP_FLASH_ATTN = "on"
DEFAULT_LLAMA_CPP_CACHE_TYPE_K = "q8_0"
DEFAULT_LLAMA_CPP_CACHE_TYPE_V = "q8_0"
DEFAULT_LLAMA_CPP_PARALLEL = 1
DEFAULT_LLAMA_CPP_FIT = "on"
DEFAULT_LLAMA_CPP_FIT_CTX = DEFAULT_LLAMA_CPP_CTX_SIZE
DEFAULT_LLAMA_CPP_FIT_TARGET = 2048
DEFAULT_LLAMA_CPP_MMAP = True
DEFAULT_LLAMA_CPP_MLOCK = False
DEFAULT_LLAMA_CPP_IMAGE_MIN_TOKENS = 1024
DEFAULT_LLAMA_CPP_IMAGE_MAX_TOKENS = 2048
DEFAULT_LLAMA_CPP_MTMD_BATCH_MAX_TOKENS = 768
